<?php

function hello_cron() {
	drupal_set_message(t('Hello cron task done'), 'warning');
}

function hello_user_login($account)
{
	drupal_set_message(t('Welcome dear %name!' , array('%name' => $account->getUsername())));
  //option 2 drupal_set_message('Welcome dear '.$account->getUsername);
}

function hello_node_update($node) {

  $database = \Drupal::database();
  $database->insert('hello_node_history')
    ->fields([
    	'nid' => $node->id(),
    	'uid' => $node->getRevisionUserId(),
    	'update_time' => $node->getChangedTime(),
    ])
    ->execute();
}

function hello_node_delete($node) {
	$database = \Drupal::database();
  $database->delete('hello_node_history')
    ->condition('nid', $node->id())
    ->execute();
}


function hello_page_attachments(array &$page){
  $page['#attached']['library'][] = 'hello/base';
}


function hello_preprocess_block(array &$variables){
  $color = \Drupal::config('hello.config')->get('color');

  $block_id = $variables["elements"]["#id"];
  $block = \Drupal\block\Entity\Block::load($block_id);
  $variables["region"] = $block->getRegion();

 if ( $variables["region"] === 'sidebar_first') {
    $variables['attributes']['class'] = $color;
  }
}

function hello_theme($existing, $type, $theme, $path) {
 return array(
   'hello_node_history' => array(
     'template'  => 'hello-node-history',
     'variables' => array(
       'node'  => NULL,
       'count' => NULL,
     ),
   ),
 );
}

function hello_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

if ($form_id == "contact_message_feedback_form") {

    $form['phone'] = array(
      '#type' => 'tel',
      '#title' => t('Phone'),
      '#required' => TRUE,
      '#weight'   => '-10'
    );
  }
}
  
