<?php

function certification_schema() {
  $schema['certification'] = array(
    'fields' => array(
      'id'=>array(
        'type'=>'serial',
        'not null' => TRUE,
      ),
      'theme'=>array(
        'type' => 'varchar',
        'length' => 40,
        'not null' => TRUE,
      ),
      'score'=>array(
        'type' => 'int',
        'length' => 2,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('id'),
  );

  return $schema;
}
